name: Deploy to server

on:
  push:
    branches:
      - main
      - preprod  # Déclenche l'action pour les branches main et preprod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      # 3. Cache Composer Dependencies
      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # 4. Install Composer Dependencies
      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      # 5. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 6. Install NPM Dependencies
      - name: Install NPM Dependencies
        run: npm install

      # 7. Build NPM Assets
      - name: Build NPM Assets
        run: npm run build

      # 8. Synchronize Files To Server (Branch-based deployment)
      - name: Synchronize Files To Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          TARGET: ${{ secrets.TARGET_PATH }}  # Variable pour déterminer le chemin en fonction de la branche

      # 9. Run Remote/Artisan Commands
      - name: Run Remote/Artisan Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

          # Choisir le répertoire de déploiement en fonction de la branche
            if [ "${GITHUB_REF##*/}" == "main" ]; then
              DEPLOY_PATH="/var/www/katanasecurity"  # Domaine principal
            elif [ "${GITHUB_REF##*/}" == "preprod" ]; then
              DEPLOY_PATH="/var/www/devkatana/katanasecurity"  # Sous-domaine préproduction
            fi

          # Exécuter les commandes artisan sur le bon répertoire
            cd $DEPLOY_PATH
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize
